// atomic/templates/settings-card.tsx
'use client'

import type { JSX } from 'react'

import {
  AdLabel,
  colorGroups,
  NucColorPicker,
  NucSettingsCard,
  resetColorsToDefault,
} from 'nucleify'

interface NucColorSettingsCardProps {
  heading?: string
}

export function NucColorSettingsCard({
  heading = 'Settings',
}: NucColorSettingsCardProps): JSX.Element {
  return (
    <NucSettingsCard
      heading={heading}
      showButton
      buttonIcon="prime:refresh"
      onButtonClick={resetColorsToDefault}
    >
      {colorGroups.map((group) => (
        <div key={group.name} className="settings-card-group">
          <h4 className="settings-card-group-title">{group.name}</h4>
          <ul className="settings-card-item-list">
            {group.items?.map((item) => (
              <li key={item} className="settings-card-item">
                <AdLabel label={item} forInput={item} />
                <NucColorPicker adType={item.toLowerCase() as AdTypeType} />
              </li>
            ))}
          </ul>
        </div>
      ))}
    </NucSettingsCard>
  )
}

// atomic/template/settings-card.vue
<template>
  <nuc-settings-card
    :heading="props.heading || 'Settings'"
    :show-button="true"
    :onButtonClick="resetColorsToDefault"
    class="settings-card"
  >
    <div
      v-for="group in colorGroups"
      :key="group.name"
      class="settings-card-group"
    >
      <h4 class="settings-card-group-title">{{ group.name }}</h4>
      <ul class="settings-card-item-list">
        <li v-for="item in group.items" :key="item" class="settings-card-item">
          <ad-label :label="item" :for="item" />
          <nuc-color-picker :ad-type="item.toLowerCase()" />
        </li>
      </ul>
    </div>
  </nuc-settings-card>
</template>

<script setup lang="ts">
import { colorGroups, resetColorsToDefault } from 'nucleify'

const props = defineProps<{
  heading: string
}>()
</script>
